[package]
name = "linear-optimisation-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
iced = "0.13.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
